=== AMWA-TV/is-06/v1.1-dev/schemas/resolved/network-address-translation.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "description": "Describes a simple network address translation policy for IP Addresses and/or Ports.",
  "title": "Network address translation policy",
  "required": [
    "id",
    "match",
    "translated",
    "receiver_endpoint_ids"
  ],
  "properties": {
    "id": {
      "description": "Globally unique identifier for translation policy",
      "type": "string",
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
    },
    "label": {
      "type": "string",
      "description": "Translation policy name."
    },
    "match": {
      "allOf": [
        {
          "dependencies": {
            "source_port": [
              "source_ip"
            ],
            "destination_port": [
              "destination_ip"
            ]
          }
        },
        {
          "$schema": "http://json-schema.org/draft-04/schema#",
          "type": "object",
          "description": "Describes the 4-tuple of IP Addresses and/or Ports to be matched or translated to.",
          "title": "Network address translation 4-tuple",
          "minProperties": 1,
          "additionalProperties": false,
          "properties": {
            "source_ip": {
              "type": "string",
              "description": "Sender IP address",
              "anyOf": [
                {
                  "format": "ipv4"
                },
                {
                  "format": "ipv6"
                }
              ]
            },
            "source_port": {
              "description": "Sender port",
              "type": "integer",
              "minimum": 1,
              "maximum": 65535
            },
            "destination_ip": {
              "type": "string",
              "description": "Destination IP address",
              "anyOf": [
                {
                  "format": "ipv4"
                },
                {
                  "format": "ipv6"
                }
              ]
            },
            "destination_port": {
              "description": "Destination port",
              "type": "integer",
              "minimum": 1,
              "maximum": 65535
            }
          }
        }
      ]
    },
    "translated": {
      "$schema": "http://json-schema.org/draft-04/schema#",
      "type": "object",
      "description": "Describes the 4-tuple of IP Addresses and/or Ports to be matched or translated to.",
      "title": "Network address translation 4-tuple",
      "minProperties": 1,
      "additionalProperties": false,
      "properties": {
        "source_ip": {
          "type": "string",
          "description": "Sender IP address",
          "anyOf": [
            {
              "format": "ipv4"
            },
            {
              "format": "ipv6"
            }
          ]
        },
        "source_port": {
          "description": "Sender port",
          "type": "integer",
          "minimum": 1,
          "maximum": 65535
        },
        "destination_ip": {
          "type": "string",
          "description": "Destination IP address",
          "anyOf": [
            {
              "format": "ipv4"
            },
            {
              "format": "ipv6"
            }
          ]
        },
        "destination_port": {
          "description": "Destination port",
          "type": "integer",
          "minimum": 1,
          "maximum": 65535
        }
      }
    },
    "receiver_endpoint_ids": {
      "type": "array",
      "description": "List of receiver endpoint IDs.",
      "items": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "minItems": 0,
      "uniqueItems": true
    }
  }
}

=== AMWA-TV/is-06/examples/netctrl-network-address-translation-patch-200.json
{
  "id": "b46fa060-a5fe-4144-94dc-24d5041c9f10",
  "label": "NAT S1-R3-video (both destination IP address and port must match for this policy to be applied)",
  "match": {
    "destination_ip": "239.1.2.3",
    "destination_port": 4500
  },
  "translated": {
    "destination_ip": "235.7.8.9",
    "destination_port": 10500
  },
  "receiver_endpoint_ids": [
    "b4aa4549-ef19-460b-9c93-76b41457af48"
  ]
}

=== AMWA-TV/is-06/examples/netctrl-network-address-translations-get-200.json
[
  {
    "id": "6b397632-d8af-4116-ad34-39ae9cc2806e",
    "label": "NAT S1-R2",
    "match": {
      "destination_ip": "239.1.2.3"
    },
    "translated": {
      "destination_ip": "235.7.8.9"
    },
    "receiver_endpoint_ids": [
      "8268e254-e054-409b-b4ab-65ee18ae684d"
    ]
  },
  {
    "id": "b46fa060-a5fe-4144-94dc-24d5041c9f10",
    "label": "NAT S1-R3-video (both destination IP address and port must match for this policy to be applied)",
    "match": {
      "destination_ip": "239.1.2.3",
      "destination_port": 4500
    },
    "translated": {
      "destination_ip": "235.7.8.9",
      "destination_port": 10500
    },
    "receiver_endpoint_ids": [
      "b4aa4549-ef19-460b-9c93-76b41457af48"
    ]
  },
  {
    "id": "4e8ff5ab-4c74-464c-8073-3d5a7f886041",
    "label": "NAT S1-R3-fec",
    "match": {
      "destination_ip": "239.1.2.3",
      "destination_port": 4510
    },
    "translated": {
      "destination_ip": "235.7.8.9",
      "destination_port": 10510
    },
    "receiver_endpoint_ids": [
      "b4aa4549-ef19-460b-9c93-76b41457af48"
    ]
  }
]
