=== AMWA-TV/is-06/v1.0.0/schemas/resolved/endpoint.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "description": "Describes an endpoint that is capable of sending or receiving network flows.",
  "required": [
    "id",
    "chassis_id",
    "port_id",
    "ip_address",
    "attached_network_device"
  ],
  "properties": {
    "id": {
      "description": "Globally unique identifier for the network endpoint",
      "type": "string",
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
    },
    "chassis_id": {
      "description": "Chassis ID of the interface, as signalled in LLDP from this endpoint. Maybe null where LLDP is unsuitable for use (ie. virtualised environments). Matches to IS-04 nodes/interfaces/chassis-id and should be same.",
      "anyOf": [
        {
          "type": "string",
          "pattern": "^([0-9a-f]{2}[-]){5}([0-9a-f]{2})$",
          "description": "When the Chassis ID is a MAC address, use this format"
        },
        {
          "type": "string",
          "pattern": "^.+$",
          "description": "When the Chassis ID is anything other than a MAC address, a freeform string may be used"
        },
        {
          "type": "null",
          "description": "When the Chassis ID is unavailable it should be set to null"
        }
      ]
    },
    "port_id": {
      "type": "string",
      "description": "MAC address of the endpoint.",
      "pattern": "^([0-9a-f]{2}[-]){5}([0-9a-f]{2})$"
    },
    "ip_address": {
      "type": "string",
      "description": "IP address on which the endpoint sends/receives flows. IP must be unique in the network.",
      "anyOf": [
        {
          "format": "ipv4"
        },
        {
          "format": "ipv6"
        }
      ]
    },
    "attached_network_device": {
      "type": "object",
      "description": "Peer network device (switch) details. This can not be an endpoint.",
      "required": [
        "chassis_id",
        "port_id"
      ],
      "properties": {
        "chassis_id": {
          "type": "string",
          "description": "MAC address for the peer network device.",
          "pattern": "^([0-9a-f]{2}[-]){5}([0-9a-f]{2})$"
        },
        "port_id": {
          "type": "string",
          "description": "The ifAlias of the peer network device the end point is connected to."
        }
      }
    },
    "max_bandwidth": {
      "type": "string",
      "pattern": "^(?:0.|[1-9][0-9]*[.])?[0-9]+[kMG]bit/s$",
      "description": "Optional. Maximum bandwidth that the sender is allowed to send. Format as numbers followed by kbit/s, Mbit/s, Gbit/s."
    },
    "role": {
      "description": "Optional with default. The role of the endpoint as a sender or receiver.",
      "type": "string",
      "enum": [
        "sender",
        "receiver",
        "both"
      ],
      "default": "both"
    },
    "label": {
      "description": "Optional. Freeform string label for the endpoint",
      "type": "string"
    }
  }
}

=== AMWA-TV/is-06/examples/netctrl-endpoints-get-200.json
[
  {
    "id": "fa08a879-488d-4e2b-8104-805e2288d8e9",
    "chassis_id": "2d-af-a9-41-01-b4",
    "port_id": "fe-97-94-bb-d2-ed",
    "ip_address": "10.10.34.44",
    "attached_network_device": {
      "chassis_id": "2f-8c-af-79-c7-00",
      "port_id": "Ethernet 1/3"
    },
    "max_bandwidth": "50Gbit/s",
    "role": "both",
    "label": "Video transmitter/receiver gateway endpoint."
  },
  {
    "id": "d9c88a0a-c0c8-4ec8-ade5-fde9106e5040",
    "chassis_id": null,
    "port_id": "58-f9-46-71-39-c2",
    "ip_address": "10.10.36.88",
    "attached_network_device": {
      "chassis_id": "2d-51-2b-85-89-7b",
      "port_id": "Ethernet 1/2"
    },
    "max_bandwidth": "10Gbit/s",
    "role": "receiver",
    "label": "Video receiver gateway endpoint."
  },
  {
    "id": "e90af02c-03ff-4a43-9cb9-4d86e0f3161a",
    "chassis_id": "58-fb-07-76-56-6b",
    "port_id": "a8-84-32-ef-1c-8c",
    "ip_address": "10.10.48.16",
    "attached_network_device": {
      "chassis_id": "72-0c-a1-2c-87-0d",
      "port_id": "Ethernet 2/2"
    },
    "max_bandwidth": "100Mbit/s",
    "role": "receiver",
    "label": "Audio receiver gateway endpoint."
  }
]
