=== AMWA-TV/is-06/v1.0.0/schemas/resolved/network-flow.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "description": "Describes a simple network flow core schema.",
  "title": "Network flow with minimal attributes",
  "required": [
    "id",
    "multicast_address",
    "sender_endpoint_id",
    "receiver_endpoint_ids",
    "bandwidth"
  ],
  "properties": {
    "id": {
      "description": "Globally unique identifier for the network flow",
      "type": "string",
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
    },
    "multicast_address": {
      "type": [
        "string",
        "null"
      ],
      "description": "Multicast group address is an ip address, the ipv4 range is 224.1.1.1 to 239.255.255.255. Provisioned for ipv6 but implementation may depend or may not exist. A null value and null type option is added for future use of this schema for unicast flow",
      "anyOf": [
        {
          "format": "ipv4"
        },
        {
          "format": "ipv6"
        },
        {
          "type": "null"
        }
      ]
    },
    "sender_endpoint_id": {
      "description": "Sender Endpoint ID",
      "type": "string",
      "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
    },
    "receiver_endpoint_ids": {
      "type": "array",
      "description": "List of receiver endpoint IDs.",
      "items": {
        "type": "string",
        "pattern": "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
      },
      "minItems": 0,
      "uniqueItems": true
    },
    "bandwidth": {
      "type": "string",
      "description": "Average bandwidth requirement for the flow. Format as numbers followed by kbit/s, Mbit/s, Gbit/s.",
      "pattern": "^(?:0.|[1-9][0-9]*[.])?[0-9]+[kMG]bit/s$"
    },
    "profile": {
      "description": "Optional with default. The transmission profile of the flow.",
      "type": "string",
      "enum": [
        "constant-rate",
        "SMPTE-2110-21-narrow",
        "SMPTE-2110-21-wide",
        "unknown"
      ],
      "default": "constant-rate"
    },
    "forward_flow": {
      "description": "Optional with default. Flag for forwarding the flow. If false, the network should not set up the flow. Only when this flag is changed to true should the flow be sent to all receivers.",
      "type": "boolean",
      "default": true
    },
    "dscp": {
      "type": "string",
      "description": "Optional with default. DSCP based QoS metrics number, default is CS0, best effort.",
      "enum": [
        "CS0",
        "CS1",
        "CS2",
        "CS3",
        "CS4",
        "CS5",
        "CS6",
        "CS7",
        "AF11",
        "AF12",
        "AF13",
        "AF21",
        "AF22",
        "AF23",
        "AF31",
        "AF32",
        "AF33",
        "AF41",
        "AF42",
        "AF43",
        "EF"
      ],
      "default": "CS0"
    },
    "label": {
      "description": "Optional. Freeform string label for the network-flow",
      "type": "string"
    }
  }
}

=== AMWA-TV/is-06/examples/netctrl-network-flow-id-get-200.json
{
  "id": "c386ff15-3b3f-4813-ac86-1c7b8cf753b6",
  "multicast_address": "226.1.1.1",
  "sender_endpoint_id": "a9ab3d49-3b8f-49e1-bbe4-b46228a9e167",
  "receiver_endpoint_ids": [
    "231ea016-1553-4488-8c2b-26bee7b9a1aa",
    "7e54a194-45e7-44e6-8795-b3a21bfff253"
  ],
  "bandwidth": "4Gbit/s",
  "profile": "SMPTE-2110-21-wide",
  "forward_flow": true,
  "dscp": "AF12",
  "label": "Sample Video network flow"
}
